import React,{useEffect,useState}from"react";
import{Percent,RefreshCw,Save,RotateCcw,LogOut,CheckCircle2,XCircle,ShipWheel,UsersRound,Bell,LifeBuoy}from"lucide-react";
import{login,providers,approveProvider,setProviderStatus,trips,setCommission,refunds,notifications,supportRequests,setSupportRequestStatus,readiness,demoCleanupPreview,cleanupDemo}from"./api.js";

function AdminBrand({login=false}){return <div className={"admin-brand"+(login?" admin-brand-login":"")}><svg className="admin-brand-mark" viewBox="0 0 64 64" aria-hidden="true"><g fill="none" stroke="#D8DEE6" strokeWidth="4.6" strokeLinecap="round" strokeLinejoin="round"><circle cx="32" cy="32" r="18"/><circle cx="32" cy="32" r="10.5"/>{[0,45,90,135,180,225,270,315].map(a=><line key={a} x1="32" y1="5.5" x2="32" y2="14" transform={`rotate(${a} 32 32)`}/>)}<path d="M25 33c3-4 6 3 9 2 2-.5 3.5-2 5-3"/></g></svg><div className="admin-brand-copy"><b>SeaGo</b><span>AQABA · ADMIN</span></div></div>}

function stored(){try{return JSON.parse(localStorage.getItem("seago_admin_auth")||"null")}catch{return null}}

function Login({onDone}) {
  const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError("");try{
    const r=await login(email.trim(),password);
    if(r.user?.role!=="admin")throw new Error("Admin account required");
    localStorage.setItem("seago_admin_auth",JSON.stringify(r));onDone(r)
  }catch(e){setError(e.message)}finally{setBusy(false)}}
  return <div className="login"><form onSubmit={submit}><AdminBrand login/><h1>Admin sign in</h1><p>Admin access only · email and password</p><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?"Please wait...":"Sign in"}</button></form></div>
}

export default function App(){
  const[auth,setAuth]=useState(stored());const[providerRows,setProviderRows]=useState([]);const[rows,setRows]=useState([]);const[refundRows,setRefundRows]=useState([]);const[notificationRows,setNotificationRows]=useState([]);const[supportRows,setSupportRows]=useState([]);const[emailStatus,setEmailStatus]=useState("all");const[emailType,setEmailType]=useState("all");const[ready,setReady]=useState(null);const[demoPreview,setDemoPreview]=useState(null);const[cleanupText,setCleanupText]=useState("");const[cleanupBusy,setCleanupBusy]=useState(false);const[cleanupMsg,setCleanupMsg]=useState("");const[tab,setTab]=useState("readiness");const[loading,setLoading]=useState(false);const[error,setError]=useState("");
  useEffect(()=>{
    const expired=()=>{setAuth(null);setProviderRows([]);setRows([]);setRefundRows([]);setNotificationRows([]);setSupportRows([]);setError("Your session expired. Please sign in again.");};
    window.addEventListener("seago:session-expired",expired);
    return()=>window.removeEventListener("seago:session-expired",expired);
  },[]);
  async function load(){if(!auth?.token)return;setLoading(true);setError("");try{const[p,t,r,n,s,rd,dp]=await Promise.all([providers(auth.token),trips(auth.token),refunds(auth.token),notifications(auth.token),supportRequests(auth.token),readiness(auth.token),demoCleanupPreview(auth.token)]);setProviderRows(p);setRows(t);setRefundRows(r);setNotificationRows(n);setSupportRows(s);setReady(rd);setDemoPreview(dp)}catch(e){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[auth?.token]);
  async function runDemoCleanup(){
    if(!demoPreview?.provider?.id&& !demoPreview?.provider?._id){setCleanupMsg("No demo provider found.");return;}
    setCleanupBusy(true);setCleanupMsg("");
    try{
      const providerId=demoPreview.provider.id||demoPreview.provider._id;
      const r=await cleanupDemo(auth.token,providerId,cleanupText);
      setCleanupMsg(r.message||"Cleanup complete.");
      setCleanupText("");
      await load();
    }catch(e){setCleanupMsg(e.message);}
    finally{setCleanupBusy(false);}
  }
  if(!auth)return <Login onDone={setAuth}/>;
  const emailTypes=[...new Set(notificationRows.map(n=>n.type).filter(Boolean))].sort();
  const emailCounts=notificationRows.reduce((a,n)=>{a.total++;a[n.status]=(a[n.status]||0)+1;return a},{total:0,sent:0,failed:0,skipped:0});
  const emailFiltered=notificationRows.filter(n=>(emailStatus==="all"||n.status===emailStatus)&&(emailType==="all"||n.type===emailType));
  const emailFailureSamples=notificationRows.filter(n=>n.status==="failed"&&n.error).slice(0,3);
  function signOut(){localStorage.removeItem("seago_admin_auth");setAuth(null);setProviderRows([]);setRows([]);setRefundRows([]);setNotificationRows([]);setSupportRows([]);}
  return <div className="app"><header><AdminBrand/><div className="admin-head-actions"><button onClick={load} disabled={loading}><RefreshCw className={loading?"spin":""} size={16}/> {loading?"Refreshing":"Refresh"}</button><button onClick={signOut}><LogOut size={16}/> Sign out</button></div></header><main>
    <div className="admin-tabs"><button className={tab==="readiness"?"active":""} onClick={()=>setTab("readiness")}>Pilot readiness</button><button className={tab==="providers"?"active":""} onClick={()=>setTab("providers")}>Providers{providerRows.filter(p=>p.status==="pending").length?` (${providerRows.filter(p=>p.status==="pending").length})`:""}</button><button className={tab==="commissions"?"active":""} onClick={()=>setTab("commissions")}>Commissions</button><button className={tab==="refunds"?"active":""} onClick={()=>setTab("refunds")}>Cancellations & refunds</button><button className={tab==="support"?"active":""} onClick={()=>setTab("support")}>Support{supportRows.filter(x=>x.status==="open").length?" ("+supportRows.filter(x=>x.status==="open").length+")":""}</button><button className={tab==="notifications"?"active":""} onClick={()=>setTab("notifications")}>Email notifications</button></div>
    {error&&<div className="error">{error}</div>}
    {loading?<p>Loading...</p>:tab==="readiness"?<>
      <div className="title"><ShipWheel/><div><small>PILOT</small><h1>Pilot readiness</h1><p>Operational checks before inviting the first real provider and customers.</p></div></div>
      {ready&&<section className="ops-overview"><div className="ops-overview-head"><div><small>OPERATIONS OVERVIEW</small><h2>All-time confirmed activity</h2><p className="ops-generated">Updated {ready.generatedAt?new Date(ready.generatedAt).toLocaleString():"just now"}</p></div><span>{ready.operations?.currency||"JOD"}</span></div><div className="ops-metrics"><div><small>Confirmed bookings</small><b>{ready.counts?.confirmedBookings||0}</b></div><div><small>Confirmed sales</small><b>{Number(ready.operations?.grossSales||0).toFixed(2)}</b></div><div><small>SeaGo commission</small><b>{Number(ready.operations?.seaGoCommission||0).toFixed(2)}</b></div><div><small>Provider net</small><b>{Number(ready.operations?.providerNet||0).toFixed(2)}</b></div></div><div className="ops-upcoming"><div className="ops-section-title"><b>Next departures</b><span>{ready.operations?.confirmedSeats||0} confirmed seats</span></div>{ready.operations?.upcoming?.length?ready.operations.upcoming.map(d=><div className="ops-departure" key={d.id}><div><b>{d.tripTitle}</b><span>{d.providerName}</span></div><div><strong>{new Date(d.startsAt).toLocaleString([],{dateStyle:"medium",timeStyle:"short"})}</strong><small>{d.reservedSeats||0}/{d.capacity} booked · {d.availableSeats} left</small></div></div>):<p className="ops-empty">No upcoming departures yet.</p>}</div></section>}
{ready&&<div className={"controlled-pilot-card "+(ready.controlledPilotReady?"ready":"blocked")}><div><small>CONTROLLED PILOT</small><h2>{ready.controlledPilotReady?"Ready for first real test":"Not ready yet"}</h2><p>{ready.controlledPilotReady?"Use one approved provider and one real customer. Payment remains test-only and no real money is charged.":"Complete the required readiness checks below before inviting a real customer."}</p></div><div className="controlled-pilot-actions"><a href="../provider/" target="_blank" rel="noreferrer">Open Provider App</a><a href="../" target="_blank" rel="noreferrer">Open Customer App</a></div>{ready.environment?.mockCheckout&&<em>Test payment mode · no real charge</em>}</div>}
{ready&&<div className="readiness-grid">
        <div className={"pilot-status "+(ready.pilotReady?"ready":"blocked")}><div><b>{ready.pilotReady?"Pilot ready":"Pilot blocked"}</b><span>{ready.pilotReady?"All required pilot checks passed. Deferred items can be completed later.":`${ready.blockers?.length||0} required check${(ready.blockers?.length||0)===1?"":"s"} still need attention.`}</span></div><em>{ready.deferredChecks?.length||0} deferred</em></div>
        {!ready.pilotReady&&ready.blockers?.length>0&&<div className="pilot-blockers"><b>Before pilot</b>{ready.blockers.map(x=><span key={x.id}>{x.label}</span>)}</div>}
        <div className="readiness-summary"><div><b>{ready.counts.providersApproved}</b><span>Approved providers</span></div><div><b>{ready.counts.activeTrips}</b><span>Active trips</span></div><div><b>{ready.counts.upcomingDepartures}</b><span>Upcoming departures</span></div><div><b>{ready.counts.confirmedBookings}</b><span>Confirmed bookings</span></div></div>
        <div className="readiness-checks">{ready.checks.map(x=><div key={x.id} className={"readiness-check "+(x.ok?"ok":x.deferred?"deferred":"bad")}>{x.ok?<CheckCircle2 size={18}/>:<XCircle size={18}/>}<span><b>{x.label}</b>{x.deferred&&!x.ok&&<small>Deferred for now</small>}</span></div>)}</div>
        <div className="readiness-env"><b>Environment</b><span>Public launch: {String(ready.environment.publicLaunch)}</span><span>Demo seed: {String(ready.environment.seedDemoData)}</span><span>Mock checkout: {String(ready.environment.mockCheckout)}</span><span>Payment provider: {ready.environment.paymentProvider}</span></div>
        <div className="demo-preview"><b>Demo cleanup</b><p>The preview below is read-only until you type the exact confirmation phrase.</p><span>Demo provider: {demoPreview?.provider?"Found":"Not found"}</span><span>Demo trips: {demoPreview?.trips?.length||0}</span><span>Demo active trips: {ready?.demo?.activeTripCount||0}</span><span>Demo departures: {demoPreview?.departureCount||0}</span><span>Demo users: {demoPreview?.users?.length||0}</span><span>Bookings linked to demo: {demoPreview?.bookingCount||0}</span><span>Checkout holds linked to demo: {demoPreview?.holdCount||0}</span>{demoPreview?.provider&&<div className="demo-cleanup-control"><small>{demoPreview?.safeToDelete?"Safe to delete demo provider data":(ready?.demo?.activeTripCount||0)===0?"Demo history is preserved and all demo trips are inactive. It no longer blocks the pilot.":"Cleanup is blocked because demo booking/hold history exists. Retire demo inventory instead of deleting history."}</small><input value={cleanupText} onChange={e=>setCleanupText(e.target.value)} placeholder="Type DELETE DEMO DATA"/><button disabled={!demoPreview?.safeToDelete||cleanupText!=="DELETE DEMO DATA"||cleanupBusy} onClick={runDemoCleanup}>{cleanupBusy?"Deleting demo data...":"Delete demo data"}</button>{cleanupMsg&&<em>{cleanupMsg}</em>}</div>}</div>
      </div>}
    </>:tab==="providers"?<>
      <div className="title"><UsersRound/><div><small>PROVIDERS</small><h1>Provider applications</h1><p>Review new SeaGo partners and approve them before they can publish trips.</p></div></div>
      <div className="provider-admin-list">{providerRows.length?providerRows.map(p=><ProviderAdminRow key={p._id} p={p} token={auth.token} onSaved={load}/>):<div className="admin-empty"><UsersRound size={28}/><b>No providers yet</b><span>New provider applications will appear here.</span></div>}</div>
    </>:tab==="commissions"?<>
      <div className="title"><Percent/><div><small>COMMISSIONS</small><h1>Trip commission control</h1><p>Only admin can change SeaGo commission. Provider apps cannot edit this value.</p></div></div>
      <div className="list">{rows.length?rows.map(t=><TripRow key={t._id} t={t} token={auth.token} onSaved={load}/>):<div className="admin-empty"><Percent size={28}/><b>No trips yet</b><span>Commission controls appear after a provider creates a trip.</span></div>}</div>
    </>:tab==="refunds"?<>
      <div className="title"><RotateCcw/><div><small>REFUNDS</small><h1>Cancellations & refunds</h1><p>Track customer and provider cancellations, refund percentages and payment status.</p></div></div>
      <div className="refund-list">{refundRows.length?refundRows.map(r=><RefundRow key={r._id} r={r}/>):<div className="admin-empty"><RotateCcw size={28}/><b>No cancellations</b><span>Refund activity will appear here when a booking is cancelled.</span></div>}</div>
    </>:tab==="support"?<>
      <div className="title"><LifeBuoy/><div><small>SUPPORT</small><h1>Customer support requests</h1><p>Tracked requests submitted from the SeaGo customer app.</p></div></div>
      <div className="support-admin-list">{supportRows.length?supportRows.map(r=><SupportRow key={r._id} r={r} token={auth.token} onSaved={load}/>):<div className="admin-empty"><LifeBuoy size={28}/><b>No support requests</b><span>Customer requests will appear here.</span></div>}</div>
    </>:<>
      <div className="title"><Bell/><div><small>EMAIL</small><h1>Email notifications</h1><p>Delivery history for confirmations, cancellations and trip reminders.</p></div></div>
      <div className="email-summary-grid"><div><small>Total</small><b>{emailCounts.total}</b></div><div className="ok"><small>Sent</small><b>{emailCounts.sent}</b></div><div className="bad"><small>Failed</small><b>{emailCounts.failed}</b></div><div className="warn"><small>Skipped</small><b>{emailCounts.skipped}</b></div></div>
      {emailCounts.failed>0&&<div className="email-alert"><b>Email delivery needs attention</b><span>{emailCounts.failed} failed event{emailCounts.failed===1?"":"s"} detected.</span>{emailFailureSamples.map((n,i)=><small key={n._id||i}>{n.error}</small>)}</div>}
      <div className="email-filters"><select value={emailStatus} onChange={e=>setEmailStatus(e.target.value)}><option value="all">All statuses</option><option value="sent">Sent</option><option value="failed">Failed</option><option value="skipped">Skipped</option></select><select value={emailType} onChange={e=>setEmailType(e.target.value)}><option value="all">All types</option>{emailTypes.map(t=><option key={t} value={t}>{t}</option>)}</select><span>{emailFiltered.length} shown</span></div>
      <div className="notification-list">{emailFiltered.length?emailFiltered.map(n=><NotificationRow key={n._id} n={n}/>):<p>No email events match these filters.</p>}</div>
    </>}
  </main></div>
}

function ProviderAdminRow({p,token,onSaved}){const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");async function approve(){setBusy(true);setMsg("");try{await approveProvider(token,p._id);setMsg("Approved");await onSaved()}catch(e){setMsg(e.message)}finally{setBusy(false)}}async function change(status){setBusy(true);setMsg("");try{await setProviderStatus(token,p._id,status);setMsg("Updated");await onSaved()}catch(e){setMsg(e.message)}finally{setBusy(false)}}const u=p.ownerUserId||{},op=p.operations||{};return <div className="provider-admin-row"><div className="provider-main"><div className="provider-admin-head"><h3>{p.businessName}</h3><em className={"provider-state "+p.status}>{p.status}</em>{p.settingsConfigured?<span className="provider-setup-ok">Setup complete</span>:<span className="provider-setup-missing">Setup incomplete</span>}</div><p>{u.name||"Provider"} · {u.email||"-"}</p><p>{p.phone||u.phone||"No phone"}</p><div className="provider-ops-grid"><div><b>{op.tripCount||0}</b><span>Trips</span></div><div><b>{op.activeTripCount||0}</b><span>Active</span></div><div><b>{op.upcomingDepartures||0}</b><span>Upcoming</span></div><div><b>{op.reservedSeatsUpcoming||0}/{op.capacityUpcoming||0}</b><span>Seats</span></div></div>{op.nextDepartureAt&&<div className="provider-next-departure"><span>Next departure</span><b>{new Date(op.nextDepartureAt).toLocaleString([],{dateStyle:"medium",timeStyle:"short"})}</b></div>}<small>Applied {p.createdAt?new Date(p.createdAt).toLocaleString():"-"}</small></div><div className="provider-admin-actions">{p.status==="pending"&&<><button disabled={busy} onClick={approve}>{busy?"Working...":"Approve provider"}</button><button className="danger" disabled={busy} onClick={()=>change("rejected")}>Reject</button></>}{p.status==="approved"&&<button className="danger" disabled={busy} onClick={()=>change("suspended")}>Suspend</button>}{p.status==="suspended"&&<><button disabled={busy} onClick={()=>change("approved")}>Reactivate</button><button className="danger" disabled={busy} onClick={()=>change("rejected")}>Reject</button></>}{p.status==="rejected"&&<button className="secondary" disabled={busy} onClick={()=>change("pending")}>Return to pending</button>}{msg&&<small>{msg}</small>}</div></div>}

function TripRow({t,token,onSaved}){
  const[value,setValue]=useState(t.pricing?.commissionType==="percentage"?t.pricing?.commissionValue:0);const[saving,setSaving]=useState(false);const[msg,setMsg]=useState("");
  async function save(){setSaving(true);setMsg("");try{await setCommission(token,t._id,Number(value));setMsg("Saved");await onSaved()}catch(e){setMsg(e.message)}finally{setSaving(false)}}
  const adultPrice=Number(t.pricing?.adultPrice??t.pricing?.pricePerPerson??0);const f=t.financials||{};const currency=f.currency||t.pricing?.currency||"JOD";
  return <div className="trip trip-financial"><div className="trip-financial-main"><div className="trip-admin-head"><h3>{t.titleEn||t.titleAr||"Untitled trip"}</h3><span className={t.active?"trip-live":"trip-off"}>{t.active?"Active":"Inactive"}</span></div><p>{t.providerId?.businessName||"Provider"} · {adultPrice.toFixed(2)} {currency}/adult</p><div className="trip-financial-grid"><div><small>Bookings</small><b>{f.confirmedBookings||0}</b></div><div><small>Seats</small><b>{f.confirmedSeats||0}</b></div><div><small>Gross sales</small><b>{Number(f.grossSales||0).toFixed(2)} {currency}</b></div><div><small>SeaGo earned</small><b>{Number(f.commissionAmount||0).toFixed(2)} {currency}</b></div><div><small>Provider net</small><b>{Number(f.providerNetAmount||0).toFixed(2)} {currency}</b></div></div></div><div className="commission"><label>SeaGo commission<input type="number" min="0" max="100" step="0.1" value={value} onChange={e=>setValue(e.target.value)}/><span>%</span></label><button onClick={save} disabled={saving}><Save size={15}/>{saving?"Saving":"Save"}</button>{msg&&<small>{msg}</small>}</div></div>
}

function RefundRow({r}){
  const c=r.cancellation||{},p=r.payment||{},impact=r.financialImpact||{};const departure=r.departureId?.startsAt?new Date(r.departureId.startsAt):null;const currency=impact.currency||r.pricing?.currency||"JOD";
  return <div className="refund-row"><div className="refund-main"><small>{r.bookingReference}</small><h3>{r.customerId?.name||"Customer"} · {r.tripId?.titleEn||r.tripId?.titleAr||"Trip"}</h3><p>{r.providerId?.businessName||"Provider"}{departure?" · "+departure.toLocaleString([],{dateStyle:"medium",timeStyle:"short"}):""}</p><p>Source: <b>{c.source||"-"}</b>{c.reason?" · "+c.reason:""}</p><div className="refund-allocation-note">Refund is actual policy output; retained allocation is estimated until production provider payouts are enabled.</div><div className="refund-financial-grid"><div><span>Original</span><b>{Number(impact.originalAmount||0).toFixed(2)} {currency}</b></div><div><span>Refund</span><b>{Number(impact.refundAmount||0).toFixed(2)} {currency}</b></div><div><span>Retained</span><b>{Number(impact.retainedAmount||0).toFixed(2)} {currency}</b></div><div><span>Est. SeaGo retained</span><b>{Number(impact.seaGoRetained||0).toFixed(2)} {currency}</b></div><div><span>Est. provider net</span><b>{Number(impact.providerNetAfterRefund||0).toFixed(2)} {currency}</b></div></div></div><div className="refund-values"><b>{c.refundPercentage||0}% refund</b><em className={"refund-status "+(c.refundStatus||"none")}>{c.refundStatus||"none"}</em><small>Payment: {p.status||"n/a"}</small>{p.refundedAmount!=null&&<small>Gateway refunded: {Number(p.refundedAmount||0).toFixed(2)} {p.currency||currency}</small>}{p.refundReference&&<small>Ref: {p.refundReference}</small>}</div></div>
}

function NotificationRow({n}){return <div className="notification-row"><div><small>{n.type}</small><h3>{n.recipient}</h3><p>{new Date(n.createdAt).toLocaleString()}</p></div><div><em className={"notification-status "+n.status}>{n.status}</em>{n.error&&<span>{n.error}</span>}{n.externalId&&<span>{n.externalId}</span>}</div></div>}

function SupportRow({r,token,onSaved}){const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");async function change(status){setBusy(true);setMsg("");try{await setSupportRequestStatus(token,r._id,status);await onSaved()}catch(e){setMsg(e.message)}finally{setBusy(false)}}const customer=r.customerId||{};return <div className="support-admin-row"><div><small>{r.bookingReference||"GENERAL SUPPORT"} · {new Date(r.createdAt).toLocaleString()}</small><h3>{r.subject}</h3><p>{r.message}</p><span>{customer.name||"Customer"}{customer.email?" · "+customer.email:""}{customer.phone?" · "+customer.phone:""}</span></div><div><em className={"support-state "+r.status}>{String(r.status||"open").replace("_"," ")}</em><select value={r.status} disabled={busy} onChange={e=>change(e.target.value)}><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select>{msg&&<small>{msg}</small>}</div></div>}
