import React,{useEffect,useState}from"react";
import{Percent,RefreshCw,Save,RotateCcw,LogOut,CheckCircle2,XCircle,ShipWheel,UsersRound,Bell,LifeBuoy,LayoutDashboard,Mail,ReceiptText,WalletCards}from"lucide-react";
import{login,providers,approveProvider,setProviderStatus,trips,setCommission,refunds,notifications,supportRequests,setSupportRequestStatus,overview,settlements,markSettlementPaid,readiness,demoCleanupPreview,cleanupDemo}from"./api.js";

function AdminBrand({login=false}){return <div className={"admin-brand"+(login?" admin-brand-login":"")}><svg className="admin-brand-mark" viewBox="0 0 64 64" aria-hidden="true"><g fill="none" stroke="#D8DEE6" strokeWidth="4.6" strokeLinecap="round" strokeLinejoin="round"><circle cx="32" cy="32" r="18"/><circle cx="32" cy="32" r="10.5"/>{[0,45,90,135,180,225,270,315].map(a=><line key={a} x1="32" y1="5.5" x2="32" y2="14" transform={`rotate(${a} 32 32)`}/>)}<path d="M25 33c3-4 6 3 9 2 2-.5 3.5-2 5-3"/></g></svg><div className="admin-brand-copy"><b>SeaGo</b><span>AQABA · ADMIN</span></div></div>}
function stored(){try{return JSON.parse(localStorage.getItem("seago_admin_auth")||"null")}catch{return null}}
function ymd(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,"0"),d=String(date.getDate()).padStart(2,"0");return `${y}-${m}-${d}`}
function rangeForPreset(preset){const today=new Date();if(preset==="all")return{from:"",to:""};if(preset==="today")return{from:ymd(today),to:ymd(today)};if(preset==="month")return{from:ymd(new Date(today.getFullYear(),today.getMonth(),1)),to:ymd(today)};const days=preset==="7d"?7:30;const from=new Date(today);from.setDate(today.getDate()-(days-1));return{from:ymd(from),to:ymd(today)}}
function Login({onDone}){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setError("");try{const r=await login(email.trim(),password);if(r.user?.role!=="admin")throw new Error("Admin account required");localStorage.setItem("seago_admin_auth",JSON.stringify(r));onDone(r)}catch(e){setError(e.message)}finally{setBusy(false)}}return <div className="login"><form onSubmit={submit}><AdminBrand login/><h1>Admin sign in</h1><p>Admin access only · email and password</p><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?"Please wait...":"Sign in"}</button></form></div>}

export default function App(){
 const[auth,setAuth]=useState(stored());const[providerRows,setProviderRows]=useState([]);const[rows,setRows]=useState([]);const[refundRows,setRefundRows]=useState([]);const[notificationRows,setNotificationRows]=useState([]);const[supportRows,setSupportRows]=useState([]);const[ready,setReady]=useState(null);const[tab,setTab]=useState("readiness");const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 async function load(){if(!auth?.token)return;setLoading(true);setError("");try{const[p,t,r,n,s,rd]=await Promise.all([providers(auth.token),trips(auth.token),refunds(auth.token),notifications(auth.token),supportRequests(auth.token),readiness(auth.token)]);setProviderRows(p);setRows(t);setRefundRows(r);setNotificationRows(n);setSupportRows(s);setReady(rd)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[auth?.token]);
 useEffect(()=>{const expired=()=>{setAuth(null);setError("Your session expired. Please sign in again.")};window.addEventListener("seago:session-expired",expired);return()=>window.removeEventListener("seago:session-expired",expired)},[]);
 if(!auth)return <Login onDone={setAuth}/>;
 function signOut(){localStorage.removeItem("seago_admin_auth");setAuth(null)}
 return <div className="app"><header><AdminBrand/><div className="admin-head-actions"><button onClick={load} disabled={loading}><RefreshCw className={loading?"spin":""} size={16}/> {loading?"Refreshing":"Refresh"}</button><button onClick={signOut}><LogOut size={16}/> Sign out</button></div></header><main><aside className="admin-tabs"><div className="admin-tabs__label">Workspace</div><button className={tab==="readiness"?"active":""} onClick={()=>setTab("readiness")}><LayoutDashboard size={17}/><span>Overview</span></button><button className={tab==="providers"?"active":""} onClick={()=>setTab("providers")}><UsersRound size={17}/><span>Providers</span></button><button className={tab==="commissions"?"active":""} onClick={()=>setTab("commissions")}><Percent size={17}/><span>Trips & fees</span></button></aside><section className="admin-content">{error&&<div className="error">{error}</div>}{loading?<div className="admin-loading"><RefreshCw className="spin" size={18}/> Loading dashboard...</div>:tab==="commissions"?<><div className="title"><Percent/><div><small>TRIPS & FEES</small><h1>Trip commission control</h1><p>SeaGo controls these fees. Providers can see them but cannot edit them.</p></div></div><div className="list">{rows.length?rows.map(t=><TripRow key={t._id} t={t} token={auth.token} onSaved={load}/>):<div className="admin-empty"><Percent size={28}/><b>No trips yet</b></div>}</div></>:tab==="providers"?<><div className="title"><UsersRound/><div><small>PROVIDERS</small><h1>Providers</h1></div></div><div className="provider-admin-list">{providerRows.map(p=><ProviderAdminRow key={p._id} p={p}/>)}</div></>:<><div className="title"><LayoutDashboard/><div><small>OVERVIEW</small><h1>SeaGo operations</h1><p>Use Trips & fees to manage provider commission agreements.</p></div></div>{ready&&<div className="overview-kpis"><div className="overview-kpi"><small>Providers</small><b>{providerRows.length}</b></div><div className="overview-kpi"><small>Trips</small><b>{rows.length}</b></div></div>}</>}</section></main></div>
}
function ProviderAdminRow({p}){return <div className="provider-admin-row"><div className="provider-main"><div className="provider-admin-head"><h3>{p.businessName}</h3><em className={"provider-state "+p.status}>{p.status}</em></div><p>{p.ownerUserId?.email||"-"}</p></div></div>}
function TripRow({t,token,onSaved}){
 const p=t.pricing||{};const fallback=Number(p.commissionValue||0);const[fees,setFees]=useState({adultCommission:Number(p.adultCommission??fallback),childCommission:Number(p.childCommission??fallback),buffetAdultCommission:Number(p.buffetAdultCommission??p.adultCommission??fallback),buffetChildCommission:Number(p.buffetChildCommission??p.childCommission??fallback)});const[saving,setSaving]=useState(false);const[msg,setMsg]=useState("");
 function field(name,label){return <label>{label}<input type="number" min="0" step="0.1" value={fees[name]} onChange={e=>setFees(v=>({...v,[name]:e.target.value}))}/><span>JOD</span></label>}
 async function save(){setSaving(true);setMsg("");try{await setCommission(token,t._id,Object.fromEntries(Object.entries(fees).map(([k,v])=>[k,Number(v)])));setMsg("Saved");await onSaved()}catch(e){setMsg(e.message)}finally{setSaving(false)}}
 const f=t.financials||{};const currency=f.currency||p.currency||"JOD";return <div className="trip trip-financial"><div className="trip-financial-main"><div className="trip-admin-head"><h3>{t.titleEn||t.titleAr||"Untitled trip"}</h3><span className={t.active?"trip-live":"trip-off"}>{t.active?"Active":"Inactive"}</span></div><p>{t.providerId?.businessName||"Provider"}{t.vesselName?" · "+t.vesselName:""}</p><div className="trip-financial-grid"><div><small>Bookings</small><b>{f.confirmedBookings||0}</b></div><div><small>Gross sales</small><b>{Number(f.grossSales||0).toFixed(2)} {currency}</b></div><div><small>SeaGo earned</small><b>{Number(f.commissionAmount||0).toFixed(2)} {currency}</b></div><div><small>Provider net</small><b>{Number(f.providerNetAmount||0).toFixed(2)} {currency}</b></div></div></div><div className="commission"><small>FIXED COMMISSION / PERSON</small>{field("adultCommission","Adult · no food")}{field("childCommission","Child · no food")}{p.buffetEnabled&&field("buffetAdultCommission","Adult · with food")}{p.buffetEnabled&&field("buffetChildCommission","Child · with food")}<button onClick={save} disabled={saving}><Save size={15}/>{saving?"Saving...":"Save fees"}</button>{msg&&<small>{msg}</small>}</div></div>
}
