import React,{useEffect,useState}from"react";
import{CalendarDays,CheckCircle2,Clock,Home,LogOut,MapPin,Pencil,Plus,QrCode,ShipWheel,Ticket,UsersRound,XCircle}from"lucide-react";
import{Html5QrcodeScanner}from"html5-qrcode";
import{login,me,trips,departures,bookings,checkIn,inspectTicket,createTrip,updateTrip,createDeparture}from"./api.js";

const CATEGORIES=["group_boat","private_boat","yacht","glass_bottom","snorkeling","diving","fishing","sunset","private_event","water_sports","semi_submarine"];
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Amman",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function authStore(){try{return JSON.parse(localStorage.getItem("seago_provider_auth")||"null")}catch{return null}}

function Login({onDone}){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setError("");try{const cleanEmail=String(email||"").trim().replace(/^mailto:/i,"");const r=await login(cleanEmail,password);if(r.user?.role!=="provider")throw new Error("Provider account required");localStorage.setItem("seago_provider_auth",JSON.stringify(r));onDone(r)}catch(e){setError(e.message)}finally{setBusy(false)}}return <div className="login"><div className="brand">Aqaba <b>SeaGo</b><span>Provider</span></div><form onSubmit={submit}><h1>Provider sign in</h1><p>Manage today's trips and scan customer tickets.</p><input type="email" inputMode="email" autoCapitalize="none" autoCorrect="off" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value.replace(/^mailto:/i,""))} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?"Signing in...":"Sign in"}</button></form></div>}

function Scanner({token,onClose,onDone}){const[result,setResult]=useState(null);const[pendingToken,setPendingToken]=useState("");const[busy,setBusy]=useState(false);useEffect(()=>{const scanner=new Html5QrcodeScanner("reader",{fps:10,qrbox:{width:240,height:240}},false);scanner.render(async decoded=>{if(busy||result)return;setBusy(true);try{if(String(decoded).startsWith("AQABA-SEAGO|BOOKING:"))throw new Error("Old ticket QR. Refresh the customer ticket page and scan the new secure QR.");const u=new URL(decoded);const t=u.searchParams.get("token");if(!t)throw new Error("Invalid SeaGo QR");const info=await inspectTicket(token,t);setPendingToken(t);setResult({mode:"preview",...info});scanner.clear().catch(()=>{});}catch(e){setResult({mode:"error",error:e.message});scanner.clear().catch(()=>{});}finally{setBusy(false)}},()=>{});return()=>{scanner.clear().catch(()=>{})}},[]);
async function confirm(){if(!pendingToken||busy)return;setBusy(true);try{const r=await checkIn(token,pendingToken);setResult({mode:"success",...r});onDone?.();}catch(e){setResult({mode:"error",error:e.message});}finally{setBusy(false)}}
const mode=result?.mode;return <div className="scanner-screen"><div className="scanner-head"><h2>Scan ticket</h2><button onClick={onClose}>×</button></div>{!result&&<div id="reader"></div>}
{mode==="preview"&&<div className="ticket-preview"><CheckCircle2 size={52}/><small>VALID TICKET</small><h2>{result.trip}</h2><div className="preview-grid"><div><span>Guest</span><b>{result.customer?.name||"Guest"}</b></div><div><span>Booking</span><b>{result.bookingReference}</b></div><div><span>Guests</span><b>{result.guests}</b></div><div><span>Departure</span><b>{result.departureAt?new Date(result.departureAt).toLocaleString([],{dateStyle:"medium",timeStyle:"short"}):"TBA"}</b></div></div>{result.customer?.phone&&<p className="contact">{result.customer.phone}</p>}<button className="confirm-checkin" disabled={!result.valid||busy} onClick={confirm}>{busy?"Checking in...":result.used?"Already checked in":"Confirm check-in"}</button><button className="secondary-scan" onClick={()=>location.reload()}>Cancel / scan another</button></div>}
{mode==="success"&&<div className="scan-result ok"><CheckCircle2 size={56}/><h2>Check-in successful</h2><p>{result.guests} guest(s) checked in</p><button onClick={()=>location.reload()}>Scan another</button></div>}
{mode==="error"&&<div className="scan-result bad"><XCircle size={56}/><h2>Ticket rejected</h2><p>{result.error}</p><button onClick={()=>location.reload()}>Scan another</button></div>}</div>}

function TripForm({token,trip,onSaved,onCancel}){const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[form,setForm]=useState(()=>({titleEn:trip?.titleEn||"",titleAr:trip?.titleAr||"",category:trip?.category||"group_boat",durationMinutes:trip?.durationMinutes||90,price:trip?.pricing?.pricePerPerson||15,commissionValue:trip?.pricing?.commissionValue||4,locationName:trip?.departureLocation?.name||"",address:trip?.departureLocation?.address||"",googleMapsUrl:trip?.departureLocation?.googleMapsUrl||"",active:trip?.active!==false}));
async function save(e){e.preventDefault();setBusy(true);setError("");const data={titleEn:form.titleEn,titleAr:form.titleAr||form.titleEn,category:form.category,durationMinutes:Number(form.durationMinutes),pricing:{currency:"JOD",pricePerPerson:Number(form.price),commissionType:"fixed_per_person",commissionValue:Number(form.commissionValue)},departureLocation:{name:form.locationName,address:form.address,googleMapsUrl:form.googleMapsUrl},active:form.active};try{if(trip)await updateTrip(token,trip._id,data);else await createTrip(token,data);onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}}
return <section className="manage-form"><div className="manage-form-head"><h2>{trip?"Edit trip":"Add new trip"}</h2><button onClick={onCancel}>×</button></div><form onSubmit={save}><label>English title<input value={form.titleEn} onChange={e=>setForm({...form,titleEn:e.target.value})} required/></label><label>Arabic title<input value={form.titleAr} onChange={e=>setForm({...form,titleAr:e.target.value})}/></label><div className="form-grid"><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{CATEGORIES.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label>Duration (min)<input type="number" min="15" value={form.durationMinutes} onChange={e=>setForm({...form,durationMinutes:e.target.value})}/></label><label>Price / person (JOD)<input type="number" min="0" step="0.5" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>SeaGo commission / person<input type="number" min="0" step="0.5" value={form.commissionValue} onChange={e=>setForm({...form,commissionValue:e.target.value})}/></label></div><label>Departure point<input value={form.locationName} onChange={e=>setForm({...form,locationName:e.target.value})} placeholder="Aqaba Marina"/></label><label>Address<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Google Maps URL<input value={form.googleMapsUrl} onChange={e=>setForm({...form,googleMapsUrl:e.target.value})}/></label><label className="toggle-row"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active trip</label>{error&&<div className="error">{error}</div>}<button className="save-button" disabled={busy}>{busy?"Saving...":"Save trip"}</button></form></section>}

function DepartureForm({token,trip,onSaved,onCancel}){const[startsAt,setStartsAt]=useState("");const[capacity,setCapacity]=useState(20);const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function save(e){e.preventDefault();setBusy(true);setError("");try{await createDeparture(token,{tripId:trip._id,startsAt:new Date(startsAt).toISOString(),capacity:Number(capacity)});onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}}return <section className="manage-form"><div className="manage-form-head"><div><small>ADD DEPARTURE</small><h2>{trip.titleEn}</h2></div><button onClick={onCancel}>×</button></div><form onSubmit={save}><label>Date & time<input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} required/></label><label>Capacity<input type="number" min="1" value={capacity} onChange={e=>setCapacity(e.target.value)} required/></label>{error&&<div className="error">{error}</div>}<button className="save-button" disabled={busy}>{busy?"Saving...":"Add departure"}</button></form></section>}

export default function App(){const[auth,setAuth]=useState(authStore());const[provider,setProvider]=useState(null);const[tab,setTab]=useState("home");const[date,setDate]=useState(today());const[tripRows,setTripRows]=useState([]);const[depRows,setDepRows]=useState([]);const[bookingRows,setBookingRows]=useState([]);const[loading,setLoading]=useState(false);const[scanner,setScanner]=useState(false);const[error,setError]=useState("");const[editingTrip,setEditingTrip]=useState(null);const[addingTrip,setAddingTrip]=useState(false);const[departureTrip,setDepartureTrip]=useState(null);
async function load(){if(!auth?.token)return;setLoading(true);setError("");try{const[p,t,d,b]=await Promise.all([me(auth.token),trips(auth.token),departures(auth.token,date),bookings(auth.token,date)]);setProvider(p);setTripRows(t);setDepRows(d);setBookingRows(b)}catch(e){setError(e.message)}finally{setLoading(false)}}
useEffect(()=>{load()},[auth?.token,date]);if(!auth)return <Login onDone={setAuth}/>;if(scanner)return <Scanner token={auth.token} onClose={()=>setScanner(false)} onDone={load}/>;
const checked=bookingRows.filter(b=>b.checkedInAt).length;const guests=bookingRows.reduce((s,b)=>s+Number(b.seats||0),0);
if(addingTrip||editingTrip)return <div className="app"><header><div className="brand">Aqaba <b>SeaGo</b><span>Provider</span></div></header><main><TripForm token={auth.token} trip={editingTrip} onCancel={()=>{setAddingTrip(false);setEditingTrip(null)}} onSaved={async()=>{setAddingTrip(false);setEditingTrip(null);await load()}}/></main></div>;
if(departureTrip)return <div className="app"><header><div className="brand">Aqaba <b>SeaGo</b><span>Provider</span></div></header><main><DepartureForm token={auth.token} trip={departureTrip} onCancel={()=>setDepartureTrip(null)} onSaved={async()=>{setDepartureTrip(null);await load()}}/></main></div>;
return <div className="app"><header><div className="brand">Aqaba <b>SeaGo</b><span>Provider</span></div><button className="logout" onClick={()=>{localStorage.removeItem("seago_provider_auth");setAuth(null)}}><LogOut size={18}/></button></header><main>
<div className="welcome"><div><small>{provider?.status==="approved"?"APPROVED PROVIDER":"PROVIDER"}</small><h1>{provider?.businessName||"SeaGo Partner"}</h1></div><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div>
{error&&<div className="error">{error}</div>}{loading?<div className="loading">Loading dashboard...</div>:<>
{tab==="home"&&<><div className="stats"><div><CalendarDays/><span><b>{depRows.length}</b> departures</span></div><div><Ticket/><span><b>{bookingRows.length}</b> bookings</span></div><div><UsersRound/><span><b>{guests}</b> guests</span></div><div><CheckCircle2/><span><b>{checked}</b> checked in</span></div></div><button className="scan-cta" onClick={()=>setScanner(true)}><QrCode size={24}/> Scan customer ticket</button><section><h2>Today's departures</h2>{depRows.length?depRows.map(d=><div className="row" key={d.id}><div><b>{d.tripId?.titleEn||d.tripId?.titleAr}</b><span><Clock size={14}/>{new Date(d.startsAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span></div><strong>{d.reservedSeats}/{d.capacity}</strong></div>):<p className="muted">No departures for this date.</p>}</section></>}
{tab==="trips"&&<section><div className="section-toolbar"><h2>My trips</h2><button onClick={()=>setAddingTrip(true)}><Plus size={16}/> Add trip</button></div>{tripRows.length?tripRows.map(t=><div className="trip-manage" key={t._id}><div><b>{t.titleEn}</b><span>{t.category.replaceAll("_"," ")} · {t.durationMinutes} min</span><span><MapPin size={13}/>{t.departureLocation?.name||"No departure point"}</span><strong>{t.pricing?.pricePerPerson} JOD / person</strong></div><div className="trip-actions"><button onClick={()=>setEditingTrip(t)}><Pencil size={15}/> Edit</button><button onClick={()=>setDepartureTrip(t)}><CalendarDays size={15}/> Add departure</button></div></div>):<p className="muted">No trips yet.</p>}</section>}
{tab==="bookings"&&<section><h2>Bookings</h2>{bookingRows.length?bookingRows.map(b=><div className="booking" key={b._id}><div><b>{b.customerId?.name||"Guest"}</b><span>{b.tripId?.titleEn||b.tripId?.titleAr}</span><span>{b.seats} guest(s) · {b.customerId?.phone||b.customerId?.email||""}</span></div><em className={b.checkedInAt?"used":"valid"}>{b.checkedInAt?"CHECKED IN":"VALID"}</em></div>):<p className="muted">No bookings for this date.</p>}</section>}
</>}</main><nav><button className={tab==="home"?"active":""} onClick={()=>setTab("home")}><Home/><span>Home</span></button><button className={tab==="trips"?"active":""} onClick={()=>setTab("trips")}><ShipWheel/><span>Trips</span></button><button className="scan" onClick={()=>setScanner(true)}><QrCode/><span>Scan</span></button><button className={tab==="bookings"?"active":""} onClick={()=>setTab("bookings")}><Ticket/><span>Bookings</span></button></nav></div>}
