import React,{useEffect,useMemo,useState}from"react";
import{CalendarDays,CheckCircle2,Clock,Home,LogOut,QrCode,ShipWheel,Ticket,UsersRound,XCircle}from"lucide-react";
import{Html5QrcodeScanner}from"html5-qrcode";
import{login,me,trips,departures,bookings,checkIn}from"./api.js";

function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Amman",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function authStore(){try{return JSON.parse(localStorage.getItem("seago_provider_auth")||"null")}catch{return null}}
function Login({onDone}){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setError("");try{const cleanEmail=String(email||"").trim().replace(/^mailto:/i,"");const r=await login(cleanEmail,password);if(r.user?.role!=="provider")throw new Error("Provider account required");localStorage.setItem("seago_provider_auth",JSON.stringify(r));onDone(r)}catch(e){setError(e.message)}finally{setBusy(false)}}return <div className="login"><div className="brand">Aqaba <b>SeaGo</b><span>Provider</span></div><form onSubmit={submit}><h1>Provider sign in</h1><p>Manage today's trips and scan customer tickets.</p><input type="email" inputMode="email" autoCapitalize="none" autoCorrect="off" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value.replace(/^mailto:/i,""))} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?"Signing in...":"Sign in"}</button></form></div>}

function Scanner({token,onClose,onDone}){const[result,setResult]=useState(null);const[busy,setBusy]=useState(false);useEffect(()=>{const scanner=new Html5QrcodeScanner("reader",{fps:10,qrbox:{width:240,height:240}},false);scanner.render(async decoded=>{if(busy)return;setBusy(true);try{if(String(decoded).startsWith("AQABA-SEAGO|BOOKING:"))throw new Error("Old ticket QR. Refresh the customer ticket page and scan the new secure QR.");const u=new URL(decoded);const t=u.searchParams.get("token");if(!t)throw new Error("Invalid SeaGo QR");const r=await checkIn(token,t);setResult({ok:true,...r});onDone?.();scanner.clear().catch(()=>{});}catch(e){setResult({ok:false,error:e.message});setBusy(false)}},()=>{});return()=>{scanner.clear().catch(()=>{})}},[]);return <div className="scanner-screen"><div className="scanner-head"><h2>Scan ticket</h2><button onClick={onClose}>×</button></div>{!result&&<div id="reader"></div>}{result&&<div className={result.ok?"scan-result ok":"scan-result bad"}>{result.ok?<CheckCircle2 size={56}/>:<XCircle size={56}/>}<h2>{result.ok?"Check-in successful":"Ticket rejected"}</h2><p>{result.ok?`${result.guests} guest(s) checked in`:result.error}</p><button onClick={()=>{setResult(null);setBusy(false);location.reload()}}>Scan another</button></div>}</div>}

export default function App(){const[auth,setAuth]=useState(authStore());const[provider,setProvider]=useState(null);const[tab,setTab]=useState("home");const[date,setDate]=useState(today());const[tripRows,setTripRows]=useState([]);const[depRows,setDepRows]=useState([]);const[bookingRows,setBookingRows]=useState([]);const[loading,setLoading]=useState(false);const[scanner,setScanner]=useState(false);const[error,setError]=useState("");
async function load(){if(!auth?.token)return;setLoading(true);setError("");try{const[p,t,d,b]=await Promise.all([me(auth.token),trips(auth.token),departures(auth.token,date),bookings(auth.token,date)]);setProvider(p);setTripRows(t);setDepRows(d);setBookingRows(b)}catch(e){setError(e.message)}finally{setLoading(false)}}
useEffect(()=>{load()},[auth?.token,date]);if(!auth)return <Login onDone={setAuth}/>;if(scanner)return <Scanner token={auth.token} onClose={()=>setScanner(false)} onDone={load}/>;
const checked=bookingRows.filter(b=>b.checkedInAt).length;const guests=bookingRows.reduce((s,b)=>s+Number(b.seats||0),0);
return <div className="app"><header><div className="brand">Aqaba <b>SeaGo</b><span>Provider</span></div><button className="logout" onClick={()=>{localStorage.removeItem("seago_provider_auth");setAuth(null)}}><LogOut size={18}/></button></header><main>
<div className="welcome"><div><small>{provider?.status==="approved"?"APPROVED PROVIDER":"PROVIDER"}</small><h1>{provider?.businessName||"SeaGo Partner"}</h1></div><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div>
{error&&<div className="error">{error}</div>}{loading?<div className="loading">Loading dashboard...</div>:<>
{tab==="home"&&<><div className="stats"><div><CalendarDays/><span><b>{depRows.length}</b> departures</span></div><div><Ticket/><span><b>{bookingRows.length}</b> bookings</span></div><div><UsersRound/><span><b>{guests}</b> guests</span></div><div><CheckCircle2/><span><b>{checked}</b> checked in</span></div></div><button className="scan-cta" onClick={()=>setScanner(true)}><QrCode size={24}/> Scan customer ticket</button><section><h2>Today's departures</h2>{depRows.length?depRows.map(d=><div className="row" key={d.id}><div><b>{d.tripId?.titleEn||d.tripId?.titleAr}</b><span><Clock size={14}/>{new Date(d.startsAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span></div><strong>{d.reservedSeats}/{d.capacity}</strong></div>):<p className="muted">No departures for this date.</p>}</section></>}
{tab==="trips"&&<section><h2>My trips</h2>{tripRows.map(t=><div className="row" key={t._id}><div><b>{t.titleEn}</b><span>{t.category.replaceAll("_"," ")} · {t.durationMinutes} min</span></div><strong>{t.pricing?.pricePerPerson} JOD</strong></div>)}</section>}
{tab==="bookings"&&<section><h2>Bookings</h2>{bookingRows.length?bookingRows.map(b=><div className="booking" key={b._id}><div><b>{b.customerId?.name||"Guest"}</b><span>{b.tripId?.titleEn||b.tripId?.titleAr}</span><span>{b.seats} guest(s) · {b.customerId?.phone||b.customerId?.email||""}</span></div><em className={b.checkedInAt?"used":"valid"}>{b.checkedInAt?"CHECKED IN":"VALID"}</em></div>):<p className="muted">No bookings for this date.</p>}</section>}
</>}</main><nav><button className={tab==="home"?"active":""} onClick={()=>setTab("home")}><Home/><span>Home</span></button><button className={tab==="trips"?"active":""} onClick={()=>setTab("trips")}><ShipWheel/><span>Trips</span></button><button className="scan" onClick={()=>setScanner(true)}><QrCode/><span>Scan</span></button><button className={tab==="bookings"?"active":""} onClick={()=>setTab("bookings")}><Ticket/><span>Bookings</span></button></nav></div>}
